### ISSUE TITLE
Define branching convention & Update project wiki

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#7]

**Comment by rr-85** [comment]
Added to the Wiki 

Contributing
Branching Name Conventions
To maintain a clear and organized repository, we follow specific naming conventions for our branches. This helps us understand the purpose of each branch at a glance and facilitates collaboration among team members. Below are the conventions we use:

Branch Types
Feature Branches: Used for developing new features.

Naming Convention: feature/<feature-name>
Example: feature/user-authentication
Bugfix Branches: Used for fixing bugs or issues in the code.

Naming Convention: bugfix/<issue-description>
Example: bugfix/fix-login-error
Hotfix Branches: Used for urgent fixes that need to be applied directly to production.

Naming Convention: hotfix/<issue-description>
Example: hotfix/correct-api-key
Chore Branches: Used for routine tasks or maintenance that do not affect the application’s features.

Naming Convention: chore/<task-description>
Example: chore/update-dependencies
General Guidelines
Use lowercase letters and hyphens to separate words for readability.
Be concise but descriptive; branch names should clearly indicate their purpose.
If the branch relates to an issue or ticket, consider including the issue number in the branch name.
Example: feature/123-add-payment-integration (where 123 is the issue number)
By following these conventions, we can ensure a more organized workflow and easier navigation of the project’s branches.
