### ISSUE TITLE
Data Ingestion & EDA

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#8]
### Objective

As a data scientist, I want to build a Python data loading script `src/data_ingestion.py` and an exploratory data analysis (EDA) notebook `eda/eda.ipynb`.

### Acceptance Criteria

- Data ingestion - Python script
    - Data loading
    - One function to read fault, scada, and status data
    - One function to merge (outer join) the three datasets
    - One function to read the ERCOT market data
- EDA - Jupyter Notebook
    - Load data from data ingestion script
    - Load in dataprep package
    - Create an EDA report showing the relationship between features

**Comment by JavierACM** [comment]
I just added context to the ticket. It's supposed to correspond to the `src/data_ingestion.py` and `eda/eda.ipynb` files. the latter is yet to be created, since I had made a .py EDA file instead.

**Comment by JavierACM** [comment]
data_ingestion.py

Possible things to work on:
- Create a class for data loading and processing: Ingestor
- Try and read merged data, and if it doesn't exist, then create merged_data file
    - Currently creates scada data on every function call

Low priority:
- Question: Could we make our read_data function better?
    - Ex: Read processed data too
