### ISSUE TITLE
HDD

### ISSUE THREAD

**Issue by ajhaller** [busi732/Team-2-2024Fall#9]

**Comment by rr-85** [comment]
[Research Plain.docx](https://github.com/user-attachments/files/17655221/Research.Plain.docx)




@gibby-ci Please provide feedback, are we following the right direction?

**Comment by ntuziyihuang** [comment]
> [Research Plain.docx](https://github.com/user-attachments/files/17655221/Research.Plain.docx)
> 
> @gibby-ci Please provide feedback, are we following the right direction?

That was a brief research plan I did last week after going over the data and our tasks?  After today's class, I think I mistook the job I should have done, but I think I can transfer that plan to object function searching or constraint functions searching. I would like to hear more advice from you professor.
